import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import FilmList from '../components/FilmList';
import { useState, useEffect } from "react";

const apiEndpoint = "https://swapi.dev/api/";

export async function getStaticProps() {
  const res = await fetch(`${apiEndpoint}films/`);
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  const [films, setFilms] = useState(data.results);

  const searchFilms = (e) => {
    e.preventDefault();
    const searchTerm = e.target.value;
    if (searchTerm) {
      const filteredFilms = films.filter((film) => {
        const searchTermLower = searchTerm.toLowerCase();
        const filmTitleLower = film.title.toLowerCase();
        return filmTitleLower.includes(searchTermLower);
      });
      setFilms(filteredFilms);
    } else {
      setFilms(data.results);
    } 
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello World</h1>
        <input type="text" placeholder="search title" onChange={searchFilms}/>
        <p className={styles.description}>
        <FilmList films={films} />
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
